name 'kreczko-arc_ce'
version '0.0.1'

author 'kreczko'
license 'Apache License, Version 2.0'
project_page 'https://github.com/HEP-Puppet'
source 'git@github.com:HEP-Puppet/puppet-arc_ce.git'
summary 'Puppet module for installation and configuration for an ARC CE'
description 'Puppet module for installation and configuration for an ARC CE'
dependency 'puppetlabs-firewall', '>=0.3.1'
